import Foundation
import Minimuxer

/// `MinimuxerError` do swift-bridge sinh ra KHÔNG tự conform `Error` (kiểm tra
/// trực tiếp trong Sources/Minimuxer/minimuxer.swift của gói SideStore/MinimuxerPackage
/// — enum khai báo trần, không có `: Error`). SideStore/SideStore tự thêm
/// conformance này trong MinimuxerWrapper.swift của họ; ở đây làm tương tự,
/// nếu không mọi `throw val.payload.err.intoSwiftRepr()` bên trong module
/// Minimuxer sẽ không biên dịch được khi module đó được dùng từ ngoài.
// MinimuxerError is generated by swift-bridge.
// The vendor-and-patch-minimuxer.sh script already adds ': Error' to its declaration
// in the vendored MinimuxerPackage to fix the "does not conform to Error" issue.
// Therefore, we do NOT need an extension here, which would cause a "already stated" warning.

/// Lớp bọc mỏng quanh các hàm FFI mà `swift-bridge` sinh ra từ crate Rust của
/// minimuxer, expose qua module `Minimuxer` (package SideStore/MinimuxerPackage).
///
/// ✅ ĐÃ XÁC NHẬN — không còn là suy đoán: đối chiếu trực tiếp với file
/// `Sources/Minimuxer/minimuxer.swift` thật trong package đó (không phải đọc
/// mã Rust rồi suy ra như trước), toàn bộ chữ ký hàm dưới đây khớp y nguyên,
/// TRỪ 2 chỗ đã sửa ở trên (`describe_error`/`fetch_udid` trả `RustString`
/// chứ không phải `String` — đã gọi `.toString()`):
///
/// ```swift
/// public func target_minimuxer_address()
/// public func start<T: IntoRustString>(_ pairing_file: T, _ log_path: T) throws -> ()
/// public func ready() -> Bool
/// public func set_debug(_ debug: Bool)
/// public func describe_error(_ error: MinimuxerError) -> RustString
/// public func fetch_udid() -> Optional<RustString>
/// public func test_device_connection() -> Bool
/// public func yeet_app_afc<T: IntoRustString>(_ bundle_id: T, _ ipa_bytes: UnsafeBufferPointer<UInt8>) throws -> ()
/// public func install_ipa<T: IntoRustString>(_ bundle_id: T) throws -> ()
/// public func remove_app<T: IntoRustString>(_ bundle_id: T) throws -> ()
/// public func install_provisioning_profile(_ profile: UnsafeBufferPointer<UInt8>) throws -> ()
/// public func remove_provisioning_profile<T: IntoRustString>(_ id: T) throws -> ()
/// ```
///
/// Ghi chú:
///   - Các hàm `throws` phía trên throw thẳng `MinimuxerError` (Swift enum),
///     không cần `.toThrowingResult()`/`RustResult` gì thêm — nhưng bản thân
///     `MinimuxerError` KHÔNG tự conform `Error` (xem extension ở trên).
///   - `String` tự conform `IntoRustString` (khai báo trong SwiftBridgeCore.swift
///     của package) nên truyền thẳng `String` vào các tham số generic `T` phía
///     trên là hợp lệ, không cần convert tay.
///   - `UnsafeBufferPointer<UInt8>` (không phải `RustByteSlice` tự tạo) — đúng
///     với `withByteSlice` bên dưới, không cần sửa gì thêm.
///   - Package còn có thêm `debug_app`, `attach_debugger`, `start_auto_mounter`,
///     `dump_profiles` chưa được bọc ở đây — có thể thêm sau nếu cần.
enum MinimuxerBridge {

    // MARK: - Lifecycle

    static func targetMinimuxerAddress() {
        target_minimuxer_address()
    }

    static func startMuxer(pairingFileContents: String, logPath: String) async throws {
        try start(pairingFileContents, logPath)
    }

    static func isReady() -> Bool {
        ready()
    }

    static func setDebugLogging(_ enabled: Bool) {
        set_debug(enabled)
    }

    static func describe(_ error: MinimuxerError) -> String {
        // describe_error trả về RustString (kiểm tra thật trong minimuxer.swift
        // sinh ra), không tự bridge sang String — cần .toString() rõ ràng.
        describe_error(error).toString()
    }

    // MARK: - Device

    static func fetchUDID() -> String? {
        // Cùng lý do với describe(): fetch_udid() trả Optional<RustString>.
        fetch_udid()?.toString()
    }

    static func testConnection() -> Bool {
        test_device_connection()
    }

    // MARK: - Install / uninstall (nguồn gốc lỗi "AFC was unable to manage files")

    /// Tương ứng `yeet_app_afc` + `install_ipa` trong install.rs — Rust tách 2
    /// bước (đẩy byte ipa vào PublicStaging qua AFC, rồi mới gọi
    /// installation_proxy cài thật) nên ở đây gọi tuần tự đúng thứ tự đó thay
    /// vì gộp làm 1, để nếu lỗi xảy ra ở bước AFC thì phân biệt được với lỗi
    /// ở bước installation_proxy.
    static func installApp(bundleID: String, ipaData: Data) async throws {
        let bytes = [UInt8](ipaData)
        try withByteSlice(bytes) { slice in
            try yeet_app_afc(bundleID, slice)
        }
        try install_ipa(bundleID)
    }

    static func uninstallApp(bundleID: String) async throws {
        try remove_app(bundleID)
    }

    // MARK: - Provisioning profile (misagent) — dùng khi chỉ cần thay profile
    // mà không cài lại toàn bộ ipa (ví dụ sau khi refresh certificate).

    static func installProvisioningProfile(_ profileData: Data) async throws {
        let bytes = [UInt8](profileData)
        try withByteSlice(bytes) { slice in
            try install_provisioning_profile(slice)
        }
    }

    static func removeProvisioningProfile(id: String) async throws {
        try remove_provisioning_profile(id)
    }

    // MARK: - Helper nội bộ

    /// Gói `[UInt8]` thành `UnsafeBufferPointer<UInt8>` đúng vòng đời cho lời
    /// gọi FFI — tách riêng 1 chỗ để nếu swift-bridge đổi tên helper
    /// (`RustByteSlice`, `.toRustByteSlice()`...) thì chỉ cần sửa Ở ĐÂY.
    private static func withByteSlice<R>(_ bytes: [UInt8], _ body: (UnsafeBufferPointer<UInt8>) throws -> R) rethrows -> R {
        try bytes.withUnsafeBufferPointer(body)
    }
}
